.PHONY: clean All

All:
	@echo "----------Building project:[ MorseLearner - Debug ]----------"
	@$(MAKE) -f  "MorseLearner.mk"
clean:
	@echo "----------Cleaning project:[ MorseLearner - Debug ]----------"
	@$(MAKE) -f  "MorseLearner.mk" clean
